export enum ACTIONS {
  SAVE_WORD = "SAVE_WORD",
  TRANSLATE_WORD = "TRANSLATE_WORD",
  DELETE_WORD = "DELETE_WORD",
  LOAD_WORDS = "LOAD_WORDS",
  LOAD_WORD = "LOAD_WORD",
  LOAD_AUDIO = "LOAD_AUDIO",
  CHANGE_SETTINGS = "CHANGE_SETTINGS",
  LOAD_SETTINGS = "LOAD_SETTINGS",
  LOAD_VOICES = "LOAD_VOICES",
  PROCESS_FILE = "PROCESS_FILE",
  BULK_UPLOAD_WORDS = "BULK_UPLOAD_WORDS",
  BULK_UPLOAD_PROGRESS = "BULK_UPLOAD_PROGRESS",
}
