export enum ACTIONS {
  SAVE_WORD = "SAVE_WORD",
  TRANSLATE_WORD = "TRANSLATE_WORD",
  DELETE_WORD = "DELETE_WORD",
  LOAD_WORDS = "LOAD_WORDS",
  LOAD_AUDIO = "LOAD_AUDIO",
  CHANGE_SETTINGS = "CHANGE_SETTINGS",
  LOAD_SETTINGS = "LOAD_SETTINGS",
  LOAD_VOICES = "LOAD_VOICES",
}
